# This is a basic workflow to help you get started with Actions

name: Unity Package

on:
  push:
    tags:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: |
          echo "Assets/Colours.meta" > metaList
          find ./Assets/Colours/ -name \*.meta >> metaList
      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          project-folder: .
          package-path: './colours.unitypackage'
          include-files: ./metaList
          
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ./colours.unitypackage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
